// dog breeds and images were taken from www.akc.org for use on this site.

var dogList = `[  
    {"breed": "Affenpinscher",
     "image": "affenpinscher.jpg"},
    {"breed": "Afghan Hound",
     "image": "afghan-hound.jpg"},
    {"breed": "Airedale Terrier",
     "image": ".jpg"},
    {"breed": "Akita",
     "image": ".jpg"},
    {"breed": "Alaskan Malamute",
     "image": ".jpg"},
    {"breed": "American English Coonhound",
     "image": ".jpg"},
    {"breed": "American Eskimo",
     "image": ".jpg"},
    {"breed": "American Foxhound",
     "image": ".jpg"},
    {"breed": "American Hairless Terrier",
     "image": ".jpg"},
    {"breed": "American Leopard Hound",
     "image": ".jpg"},
    {"breed": "American Staffordshire Terrier",
     "image": ".jpg"},
    {"breed": "American Water Spaniel",
     "image": ".jpg"},
    {"breed": "Anatolian Shepherd",
     "image": ".jpg"},
    {"breed": "Appenzeller Sennenhund",
     "image": ".jpg"},
    {"breed": "Australian Cattle",
     "image": ".jpg"},
    {"breed": "Australian Kelpie",
     "image": ".jpg"},
    {"breed": "Australian Shepherd",
     "image": ".jpg"},
    {"breed": "Australian Stumpy Tail Cattle",
     "image": ".jpg"},
    {"breed": "Australian Terrier",
     "image": ".jpg"},
    {"breed": "Azawakh",
     "image": ".jpg"},
    {"breed": "Barbet",
     "image": ".jpg"},
    {"breed": "Basenji",
     "image": ".jpg"},
    {"breed": "Basset Fauve de Bretagne",
     "image": ".jpg"},
    {"breed": "Basset Hound",
     "image": ".jpg"},
    {"breed": "Bavarian Mountain Scent Hound",
     "image": ".jpg"},
    {"breed": "",
     "image": ".jpg"},
    {"breed": "",
     "image": ".jpg"},
                
{}
]`;


